version: "1"

databases:
  - name: ops-postgres
    plan: free
    databaseName: opsdb
    user: opsuser

services:
  # ---------------------------
  # Customers Service
  # ---------------------------
  - type: web
    name: customers-svc
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: customers-svc/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ops-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ops-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ops-postgres
          property: password

  # ---------------------------
  # Technicians Service
  # ---------------------------
  - type: web
    name: technicians-svc
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: technicians-svc/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ops-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ops-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ops-postgres
          property: password
      - key: CUSTOMERS_BASE_URL
        value: https://__CUSTOMERS_URL__
      - key: AUTH_BASE_URL
        value: https://__AUTH_URL__

  # ---------------------------
  # Supervisors Service
  # ---------------------------
  - type: web
    name: supervisors-svc
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: supervisors-svc/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ops-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ops-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ops-postgres
          property: password
      - key: USERS_BASE_URL
        value: https://__AUTH_URL__
      - key: AUTH_BASE_URL
        value: https://__AUTH_URL__

  # ---------------------------
  # Visits Service
  # ---------------------------
  - type: web
    name: visits-svc
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: visits-svc/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ops-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ops-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ops-postgres
          property: password
      - key: CUSTOMERS_BASE_URL
        value: https://__CUSTOMERS_URL__
      - key: TECHNICIANS_BASE_URL
        value: https://__TECHNICIANS_URL__
      - key: SUPERVISORS_BASE_URL
        value: https://__SUPERVISORS_URL__
      - key: VISITS_MAIL_ENABLED
        value: "false"
      - key: VISITS_MAIL_FROM
        value: no-reply@visits.local
      - key: VISITS_MAIL_DEFAULT_TO
        value: test@demo.local

  # ---------------------------
  # Web Portal
  # ---------------------------
  - type: web
    name: web-portal
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: web-portal/Dockerfile
    healthCheckPath: /
    envVars:
      - key: CUSTOMERS_BASE_URL
        value: https://__CUSTOMERS_URL__
      - key: TECHNICIANS_BASE_URL
        value: https://__TECHNICIANS_URL__
      - key: SUPERVISORS_BASE_URL
        value: https://__SUPERVISORS_URL__
      - key: VISITS_BASE_URL
        value: https://__VISITS_URL__
      - key: AUTH_BASE_URL
        value: https://__AUTH_URL__
