version: "1"

databases:
  - name: ops-postgres
    plan: free
    databaseName: opsdb
    user: opsuser

services:
  - type: web
    name: customers-svc
    plan: free
    runtime: docker
    dockerfilePath: customers-svc/Dockerfile
    dockerContext: .
    rootDir: .
    branch: main
    region: frankfurt
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }
      - key: AUTH_BASE_URL
        value: https://tu-auth-en-render.onrender.com