version: "1"

databases:
  - name: ops-postgres
    plan: free
    databaseName: opsdb
    user: opsuser

services:
  - type: web
    name: customers-svc
    plan: free
    runtime: image
    image:
      url: docker.io/eclipse-temurin:17-jdk
    rootDir: customers-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :customers-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ops-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ops-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ops-postgres
          property: password