version: "1"
previews:
  generation: automatic

databases:
  - name: ops-postgres
    plan: free
    databaseName: opsdb
    user: opsuser

services:
  # ──────────────────────────────────────────────────────────────────────────
  # customers-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: customers-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: customers-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :customers-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }

  # ──────────────────────────────────────────────────────────────────────────
  # technicians-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: technicians-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: technicians-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :technicians-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }

  # ──────────────────────────────────────────────────────────────────────────
  # contacts-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: contacts-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: contacts-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :contacts-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }

  # ──────────────────────────────────────────────────────────────────────────
  # sites-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: sites-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: sites-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :sites-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }

  # ──────────────────────────────────────────────────────────────────────────
  # tickets-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: tickets-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: tickets-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :tickets-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }
      - key: CUSTOMERS_BASE_URL
        value: https://customers-svc.onrender.com
      - key: TECHNICIANS_BASE_URL
        value: https://technicians-svc.onrender.com
      - key: SITES_BASE_URL
        value: https://sites-svc.onrender.com

  # ──────────────────────────────────────────────────────────────────────────
  # work-orders-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: work-orders-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: work-orders-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :work-orders-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }
      - key: TICKETS_BASE_URL
        value: https://tickets-svc.onrender.com

  # ──────────────────────────────────────────────────────────────────────────
  # assets-svc
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: assets-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: assets-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :assets-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }
      - key: CUSTOMERS_BASE_URL
        value: https://customers-svc.onrender.com

  # ──────────────────────────────────────────────────────────────────────────
  # visits-svc (email)
  # ──────────────────────────────────────────────────────────────────────────
  - type: web
    name: visits-svc
    plan: free
    runtime: image
    image: eclipse-temurin:17-jdk
    rootDir: visits-svc
    branch: main
    region: frankfurt
    buildCommand: ./gradlew :visits-svc:bootJar -x test
    startCommand: java -jar build/libs/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: { name: ops-postgres, property: connectionString }
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: { name: ops-postgres, property: user }
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: { name: ops-postgres, property: password }
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
      - key: VISITS_MAIL_FROM
        value: no-reply@visits.local
      - key: VISITS_MAIL_TO
        value: test@demo.local
      - key: CUSTOMERS_BASE_URL
        value: https://customers-svc.onrender.com
      - key: TECHNICIANS_BASE_URL
        value: https://technicians-svc.onrender.com
      - key: SITES_BASE_URL
        value: https://sites-svc.onrender.com